config/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import django_prometheus.urls
from django.urls import path

from qabel_web_theme import urls as theme_urls

from index_service import views
from index_service import verification


rest_urls = [
    url(r'^$', views.api_root, name='api-root'),
    url(r'^key/$', views.key, name='api-key'),
    url(r'^search/$', views.search, name='api-search'),
    url(r'^update/$', views.update, name='api-update'),
    url(r'^status/$', views.status, name='api-status'),
    url(r'^delete-identity/$', views.delete_identity, name='api-delete-identity'),
]

verification_urls = [
    url(r'^(?P<id>[^/]+)/(?P<action>confirm|deny)/$', verification.verify, name='verify'),
    url(r'^(?P<id>[^/]+)/$', verification.review, name='review'),
]

urlpatterns = [
    url(r'^$', verification.index),
    path(r'admin/', admin.site.urls),
    url(r'^api/v0/', include(rest_urls)),
    url(r'^verify/', include(verification_urls)),
    url('', include(django_prometheus.urls)),
    url(r'^', include(theme_urls)),
]

qabel_index/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import django_prometheus.urls

from qabel_web_theme import urls as theme_urls

from index_service import views
from index_service import verification


rest_urls = [
    url(r'^$', views.api_root, name='api-root'),
    url(r'^key/$', views.key, name='api-key'),
    url(r'^search/$', views.search, name='api-search'),
    url(r'^update/$', views.update, name='api-update'),
    url(r'^status/$', views.status, name='api-status'),
    url(r'^delete-identity/$', views.delete_identity, name='api-delete-identity'),
]

verification_urls = [
    url(r'^(?P<id>[^/]+)/(?P<action>confirm|deny)/$', verification.verify, name='verify'),
    url(r'^(?P<id>[^/]+)/$', verification.review, name='review'),
]

urlpatterns = [
    url(r'^$', verification.index),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/v0/', include(rest_urls)),
    url(r'^verify/', include(verification_urls)),
    url('', include(django_prometheus.urls)),
    url(r'^', include(theme_urls)),
]

qabel_register/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from register_service import views
from register_service import verification


rest_urls = [
    url(r'^$', views.api_root, name='api-root'),
    url(r'^key/$', views.key, name='api-key'),
    url(r'^search/$', views.search, name='api-search'),
    url(r'^update/$', views.update, name='api-update'),
]

verification_urls = [
    url(r'^(?P<id>[^/]+)/(?P<action>confirm|deny)/$', verification.verify, name='verify'),
    url(r'^(?P<id>[^/]+)/$', verification.review, name='review'),
]

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/v0/', include(rest_urls)),
    url(r'^verify/', include(verification_urls)),
]

index_service/models.py
import json

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from django_prometheus.models import ExportModelOperationsMixin

from .utils import short_id


class CreationTimestampModel(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name=_('creation timestamp field'))

    class Meta:
        abstract = True


class Identity(ExportModelOperationsMixin('Identity'), CreationTimestampModel):
    """
    An identity, composed of the public key, drop URL and alias.

    This is the only kind of data the register server is allowed to return to clients.
    """

    public_key = models.CharField(max_length=64, db_index=True, unique=True)
    alias = models.CharField(max_length=255)
    drop_url = models.URLField()

    class Meta:
        verbose_name = _('identity model')
        verbose_name_plural = _('identities model plural')

    def delete_if_garbage(self):
        """Clean up this identity if there are no entries referring to it."""
        if not self.entry_set.count():
            self.delete()

    def __repr__(self):
        return 'alias: {} public_key: {}'.format(self.alias, repr(self.public_key))

    __str__ = __repr__


class Entry(ExportModelOperationsMixin('Entry'), CreationTimestampModel):
    """
    An Entry connects a piece of private data (email, phone, ...) to an identity.

    Clients query the register server with private data to find associated public identities.
    """

    FIELDS_CHOICES = (
        ('email', _('E-Mail address')),
        ('phone', _('Phone number')),
    )

    # These are the fields a client can search for
    FIELDS = {'email', 'phone'}

    field = models.CharField(max_length=30, db_index=True, choices=FIELDS_CHOICES)
    value = models.CharField(max_length=200)
    identity = models.ForeignKey(Identity, on_delete=models.CASCADE)

    def __str__(self):
        return '{}: {}'.format(self.field, self.value)

    class Meta:
        index_together = ('field', 'identity')
        unique_together = ('field', 'identity')
        verbose_name = _('entry model')
        verbose_name_plural = _('entries model plural')


class PendingUpdateRequest(ExportModelOperationsMixin('PendingUpdateRequest'), CreationTimestampModel):
    """
    Pending update request: When additional user-asynchronous authorization is required a request has
    to be stored in the database (and all verifications have to complete) before it can be executed.

    If a request is received for which a verification is needed, it is saved as a PendingUpdateRequest and for each
    verification required a corresponding PendingVerification object is created.

    Verification handlers remove a PendingVerification if it succeeded, if no other verifications are pending for
    the request it is then executed.

    When a verification fails, the handler deletes the PendingRequest and all other PendingVerifications;
    the request has failed. There must be no notification mechanism to the requester, since the requester is
    not authenticated.

    Pending requests expire automatically after settings.PENDING_REQUEST_MAX_AGE.
    """

    public_key = models.CharField(max_length=64, verbose_name=_('public key of request identity'), db_index=True)

    # JSON-serialized request
    _json_request = models.TextField()

    @property
    def request(self):
        return json.loads(self._json_request)

    @request.setter
    def request(self, value):
        self._json_request = json.dumps(value)

    submit_date = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.public_key = self.request['identity']['public_key']
        super().save(*args, **kwargs)

    def is_expired(self):
        if timezone.now() - self.submit_date >= settings.PENDING_REQUEST_MAX_AGE:
            return True
        return False

    def __str__(self):
        return '{}: {}'.format(self.created.replace(microsecond=0).isoformat(' '),
                               ', '.join(pv.id for pv in self.pendingverification_set.all()))

    class Meta:
        verbose_name = _('pending update request model')
        verbose_name_plural = _('pending update request model plural')


class PendingVerification(ExportModelOperationsMixin('PendingVerification'), models.Model):
    """
    A pending verification, e.g. a confirmation mail or SMS that has not been acted upon yet.
    """

    @classmethod
    def get_factory(cls, pending_request):
        def factory(id=None):
            while True:
                id = id or short_id(10)
                if cls.objects.filter(id=id).count():
                    id = None
                    continue
                break
            instance = cls(id=id, request=pending_request)
            instance.save()
            return instance
        return factory

    id = models.CharField(max_length=36, primary_key=True)
    request = models.ForeignKey(PendingUpdateRequest, on_delete=models.CASCADE)

    def _update_state(self, state):
        id = self.id
        self.delete()
        dv, _ = DoneVerification.objects.get_or_create(id=id, defaults={'state': state})
        dv.state = state
        dv.save()

    def confirmed(self):
        self._update_state('confirmed')

    def denied(self):
        self._update_state('denied')

    def expired(self):
        self._update_state('expired')

    def _url(self, action):
        return reverse('verify', kwargs={
            'id': self.id,
            'action': action,
        })

    @property
    def confirm_url(self):
        return self._url('confirm')

    @property
    def deny_url(self):
        return self._url('deny')

    @property
    def review_url(self):
        return reverse('review', kwargs={
            'id': self.id
        })

    class Meta:
        verbose_name = _('pending verification model')
        verbose_name_plural = _('pending verification model plural')


class DoneVerification(ExportModelOperationsMixin('DoneVerification'), CreationTimestampModel):
    STATES = (
        ('confirmed', _('Confirmed')),
        ('denied', _('Denied')),
        ('expired', _('Expired')),
    )
    id = models.CharField(max_length=36, primary_key=True)
    state = models.CharField(max_length=20, choices=STATES)

    class Meta:
        verbose_name = _('done verification model')
        verbose_name_plural = _('done verification model plural')

index_service/templates/codeentry.html
{% extends "index.html" %}
{% load i18n bootstrap %}

{% block title %}Qabel Index{% endblock %}

{% block content %}
    {{ block.super }}
    <form method="post" class="form-horizontal">
        {% csrf_token %}
        <legend>
            {% trans "Enter the confirmation code you received to proceed" %}
        </legend>

        {{ form|bootstrap_horizontal }}

        <div class="form-group">
          <div class="col-sm-10 col-sm-offset-2">
            <input type="submit" class="btn btn-primary" value="{% trans 'Review' %}">
          </div>
        </div>
    </form>
{% endblock %}

index_service/templates/index.html
{% extends "base.html" %}

{% block title %} – Qabel Index{% endblock %}

{% block content %}<p>&nbsp;</p>{% endblock %}

index_service/templates/request_expired.html
{% extends "index.html" %}
{% load i18n %}

{% block title %}{% trans "Request has expired" %}{{ block.super }}{% endblock %}

{% block content %}
    <h2>{% trans "This request has expired." %}</h2>
{% endblock %}

index_service/templates/request_status.html
{% extends "index.html" %}
{% load i18n %}

{% block title %}
{% if status == 'confirmed' %}{% trans "Request confirmed" %}
{% else %}
{% trans "Request denied" %}
{% endif %}
{{ block.super }}{% endblock %}

{% block content %}
{% if status == 'confirmed' %}
<h2>{% trans "Confirmed Qabel Index entry." %}</h2>
{% else %}
<h2>{% trans "Denied Qabel Index entry." %}</h2>
{% endif %}
{% endblock %}

index_service/templates/review.html
{% extends "index.html" %}
{% load i18n bootstrap %}

{% block title %}{% trans "Review entry" %}{{ block.super }}{% endblock %}

{% block content %}
    {{ block.super }}
    <form method="post" class="form-horizontal">
        {% csrf_token %}
        <legend>
            {% trans "Review entry" %}
        </legend>

        <div class="form-group">
            <div class="col-sm-2">{% trans "Identity" %}</div>
            <div class="col-sm-10">
                {% trans "alias label" %} {{ identity.alias }}<br/>
                {% trans "public key label" %} {{ identity.public_key }}
            </div>
        </div>

        {% comment %}
        {% for item in items %}
        <div class="form-group">
            <div class="col-sm-2">
                {% if item.action == 'create' %}
                    {% blocktrans with field=item.get_field_display %}Unpublish {{ field }}{% endblocktrans %}
                {% else %}
                    {% blocktrans with field=item.get_field_display %}Publish {{ field }}{% endblocktrans %}
                {% endif %}
            </div>
            <div class="col-sm-10">
                {{ item.value }}
            </div>
        </div>
        {% endfor %}
        {% endcomment %}

        <div class="form-group">
            <div class="col-sm-10 col-sm-offset-2">
                <button type="submit" name="action" value="deny" class="btn btn-primary">{% trans 'Deny' %}</button>
                <button type="submit" name="action" value="confirm" class="btn btn-primary">{% trans 'Confirm' %}</button>
            </div>
        </div>
    </form>
{% endblock %}